/**
  ******************************************************************************
  * @file    main.c
  * @author  Auto-generated by STM32CubeIDE
  * @version V1.0
  * @brief   Default main function.
  ******************************************************************************
*/

#include<stdint.h>

#define RCC_BASE_ADDR				0x40023800UL

#define RCC_CFGR_REG_OFFSET			0x08UL

#define RCC_CFGR_REG_ADDR			(RCC_BASE_ADDR + RCC_CFGR_REG_OFFSET)

#define RCC_AHB1ENR_OFFSET			0x30UL

#define RCC_AHB1ENR_ADDR			(RCC_AHB1ENR_OFFSET + RCC_BASE_ADDR)

#define GPIOA_BASE_ADDR				0x40020000UL

#define GPIOA_MODER_ADDR			GPIOA_BASE_ADDR
// GPIO AFRLHigh
#define GPIOA_AFRL_OFFSET			0x24UL

#define GPIOA_AFRL_ADDR				(GPIOA_AFRL_OFFSET + GPIOA_BASE_ADDR)

#define GPIOA_IDR_OFFSET			0x10UL

#define GPIOA_IDR_ADDR				(GPIOA_IDR_OFFSET + GPIOA_BASE_ADDR)

int main(void)
{

	//	1. Configure RCC_CFGR MC01 Bit fields to select HSI(high speed internal/RC) clock source
	uint32_t *p_rccCFGR = (uint32_t*)RCC_CFGR_REG_ADDR;
	*p_rccCFGR &= ~(0x3<<21);

	//Configure MCO1 pre-scaler
	*p_rccCFGR|= (6<<24);

	//	2. Configure RCC_AHB1ENR to enable clock to GPIOA port
	uint32_t *p_rccAHB1ENR = (uint32_t*)RCC_AHB1ENR_ADDR;
	*p_rccAHB1ENR |= (1<<0);

	// 3. Configure GPIOA_MODER to set PA8 to alternate function mode
	uint32_t *p_GPIOA_MODER = (uint32_t*)GPIOA_MODER_ADDR;
	*p_GPIOA_MODER &= ~(0xF<<16); //Clear
	*p_GPIOA_MODER |= (0x2<<16); //Set

	// 4. Configure GPIOA_AFRLHigh to enable alternate function 0 (AF0)
	uint32_t *p_GPIOA_AFRL = (uint32_t*)GPIOA_AFRL_ADDR;
	*p_GPIOA_AFRL &= ~(0x0F);

	// EXTRA to cycle clock speeds

	// Configure PA0 for PB input
	*p_GPIOA_MODER &= ~0xF;


	uint32_t *p_GPIOA_IDR = (uint32_t*)GPIOA_IDR_ADDR;


	uint8_t prevState = 0;

		while(1) {
		    uint8_t speedSelect = (uint8_t)(*p_GPIOA_IDR & 1);

		    // One-shot: only run if previous was 0 and current is 1
		    if (!prevState && speedSelect) {

		        uint32_t clearCFG = *p_rccCFGR & ~(0x7<<24);
		        uint32_t nextState = (*p_rccCFGR & 0x7<<24) + (1<<24);
		        if((nextState > 0) && (nextState < (4<<24))) nextState = 0x4<<24;
		        *p_rccCFGR = clearCFG | nextState;

		    }

		    prevState = speedSelect;
		}


	}


}
